### ISSUE TITLE
Add Users with CSV file and include Delete Functionality

### ISSUE THREAD

**Issue by syavatkar** [DSpeichert/cloudvcl#35] opened 2017-04-20 01:25 UTC
Included Add Functionality to upload users from CSV file.

I am still confused as to how we are including this delete functionality. Are we using the csv files to also delete users or should there only be delete functionality included with all users from the database listed? @DSpeichert

**Comment by DSpeichert** [comment] 2017-04-20 01:30
Where did you include add functionality? Why are you mentioning it in this issue?

We are not deleting users. We are only removing a user from a course.

**Comment by DSpeichert** [comment] 2017-04-25 00:21
Duplicate of #22

**Closed as completed by DSpeichert** 2017-04-25 00:21 UTC
